import os
import re
import time
import requests
import random
import urllib.parse
import json
from datetime import datetime
from flask import Flask, render_template, request, session, send_from_directory, url_for
import google.generativeai as genai
from openai import OpenAI
from pptx import Presentation
from pptx.util import Inches, Pt
from dotenv import load_dotenv

load_dotenv()

app = Flask(__name__)
app.secret_key = "marketai_secret_key"

# Configure Gemini
genai.configure(api_key=os.environ.get("GEMINI_API_KEY"))
# Using gemini-flash-latest as gemini-1.5-flash was not found in this environment
model = genai.GenerativeModel('gemini-flash-latest')

# Configure OpenAI
client = OpenAI(api_key=os.environ.get("OPENAI_API_KEY"))

def add_activity(title, description, icon="✨"):
    from flask import session
    from datetime import datetime
    if 'activities' not in session:
        session['activities'] = []
    
    activity = {
        'title': title,
        'description': description,
        'icon': icon,
        'time': datetime.now().strftime("%I:%M %p")
    }
    
    # Keep only the last 3 activities
    session['activities'].insert(0, activity)
    session['activities'] = session['activities'][:3]
    session.modified = True

# Reusable AI function using Gemini
def generate_response(prompt):
    try:
        response = model.generate_content(prompt)
        return response.text
    except Exception as e:
        return f"Error connecting to Gemini API: {str(e)}"

# Professional Logo Generation (Fast & Accurate)
def generate_brand_logo(prompt):
    try:
        # Using Flux model via Pollinations for speed and high accuracy 
        # (Reliable alternative to OpenAI billing limits)
        print(f"Generating high-speed logo for: {prompt}")
        
        # Craft a precise visual prompt
        final_prompt = f"Professional minimalist logo, {prompt}, masterpiece, clean lines, white background, commercial quality"
        seed = random.randint(1, 1000000)
        encoded_prompt = urllib.parse.quote(final_prompt)
        
        # Pollinations Flux is fast and high-quality
        image_url = f"https://gen.pollinations.ai/image/{encoded_prompt}?width=1024&height=1024&nologo=true&seed={seed}&model=flux"
        
        return save_image_as_jpeg(image_url)
    except Exception as e:
        print(f"Logo Generation Error: {e}")
        return None

def save_image_as_jpeg(image_url):
    try:
        # Download image
        response = requests.get(image_url, timeout=25)
        if response.status_code != 200:
            return None
            
        img_data = response.content
        filename = f"logo_{int(time.time())}.jpg"
        
        gen_dir = os.path.join(app.static_folder, 'generated')
        if not os.path.exists(gen_dir):
            os.makedirs(gen_dir)
            
        filepath = os.path.join(gen_dir, filename)
        
        # Save as JPEG
        with open(filepath, 'wb') as f:
            f.write(img_data)
            
        return filename
    except Exception as e:
        print(f"Save JPEG Error: {e}")
        return None

# PPTX Generation Logic
def create_pptx_file(deck_data, filename):
    prs = Presentation()
    
    # Title Slide
    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    title = slide.shapes.title
    subtitle = slide.placeholders[1]
    
    title.text = deck_data.get("title", "Pitch Deck")
    subtitle.text = deck_data.get("subtitle", "Generated by MarketAI Suite")
    
    # Content Slides
    bullet_slide_layout = prs.slide_layouts[1]
    for slide_data in deck_data.get("slides", []):
        slide = prs.slides.add_slide(bullet_slide_layout)
        shapes = slide.shapes
        title_shape = shapes.title
        body_shape = shapes.placeholders[1]
        
        title_shape.text = slide_data.get("title", "Slide")
        
        tf = body_shape.text_frame
        tf.word_wrap = True
        
        for point in slide_data.get("content", []):
            p = tf.add_paragraph()
            p.text = str(point)
            p.level = 0

    # Ensure directory exists
    gen_dir = os.path.join(app.static_folder, 'generated')
    if not os.path.exists(gen_dir):
        os.makedirs(gen_dir)
        
    filepath = os.path.join(gen_dir, filename)
    prs.save(filepath)
    return filename

def generate_pptx_content(product_name, description, audience):
    prompt = f"""
    You are an expert pitch deck consultant. Create a structured 7-slide pitch deck for the following:
    Product: {product_name}
    Description: {description}
    Target Audience: {audience}
    
    Respond STRICTLY in JSON format with this structure:
    {{
        "title": "Main Title",
        "subtitle": "Subtitle/Catchphrase",
        "slides": [
            {{
                "title": "Slide Title",
                "content": ["Bullet point 1", "Bullet point 2", "Bullet point 3"]
            }}
        ]
    }}
    
    Required slides:
    1. Title (Already handled by root)
    2. The Problem
    3. The Solution
    4. Market Opportunity
    5. Core Features
    6. Business Model
    7. Call to Action
    
    Ensure the JSON is valid and only return the JSON block.
    """
    try:
        response = model.generate_content(prompt)
        # Attempt to find JSON block more robustly
        text = response.text
        # Remove markdown code blocks if present
        text = re.sub(r'```(?:json)?', '', text)
        text = re.sub(r'```', '', text)
        
        json_match = re.search(r'(\{.*\})', text, re.DOTALL)
        if json_match:
            return json.loads(json_match.group(1))
        return json.loads(text.strip())
    except Exception as e:
        print(f"Gemini JSON Error: {e}")
        # Log the raw text for debugging if needed
        # print(f"Raw response: {response.text}")
        return None

# Home Page
@app.route("/")
def home():
    return render_template("index.html")

# Campaign Generator
@app.route("/campaign", methods=["GET", "POST"])
def campaign():
    output = None
    if request.method == "POST":
        product = request.form["product"]
        audience = request.form["audience"]
        platform = request.form["platform"]

        prompt = f"""
        You are a marketing strategist.
        
        Create a marketing campaign for:
        Product: {product}
        Target Audience: {audience}
        Platform: {platform}
        
        Respond strictly in this format:
        
        1. Campaign Objectives:
        2. Target Positioning:
        3. 5 Content Ideas:
        4. 3 Ad Copies:
        5. Call-To-Action:
        """
        output = generate_response(prompt)
        if "Error" not in output:
            add_activity("Campaign Generated", f"Strategy created for {product}", icon="🚀")
    return render_template("campaign.html", output=output)

# Sales Pitch Generator
@app.route("/pitch", methods=["GET", "POST"])
def pitch():
    output = None
    if request.method == "POST":
        product = request.form["product"]
        persona = request.form["persona"]
        industry = request.form.get("industry", "Not specified")
        size = request.form.get("size", "Not specified")
        budget = request.form.get("budget", "Not specified")
        
        prompt = f"""
        You are a B2B sales expert.
        
        Create a sales pitch for:
        Product: {product}
        Customer Persona: {persona}
        Industry: {industry}
        Company Size: {size}
        Budget Range: {budget}
        
        Respond strictly in this format:
        
        1. 30-Second Elevator Pitch:
        2. Core Value Proposition:
        3. Key Differentiators:
        4. Business Impact:
        5. Call-To-Action:
        """
        output = generate_response(prompt)
        if "Error" not in output:
            add_activity("Sales Pitch Crafted", f"Pitch for {persona[:30]}...", icon="💼")
    return render_template("pitch.html", output=output)

import re

# Lead Scoring
@app.route("/lead", methods=["GET", "POST"])
def lead():
    output = None
    score = 0
    probability = 0
    if request.method == "POST":
        name = request.form["name"]
        budget = request.form["budget"]
        need = request.form["need"]
        urgency = request.form["urgency"]
        notes = request.form.get("notes", "None")

        prompt = f"""
        You are a sales qualification expert.
        
        Analyze the following lead:
        Name: {name}
        Budget: {budget}
        Need: {need}
        Urgency: {urgency}
        Additional Notes: {notes}
        
        Score using:
        Budget (25)
        Need (30)
        Urgency (20)
        Authority/Fit (25)
        
        Respond strictly in this format:
        
        1. Final Score (0-100): [Score]
        2. Score Breakdown:
        3. Category:
        4. Conversion Probability (%):
        5. Recommended Action:
        """
        output = generate_response(prompt)
        
        # Extract score and probability
        try:
            score_match = re.search(r"Final Score.*?:.*?(\d+)", output)
            if score_match:
                score = int(score_match.group(1))
        except:
            score = 0

        try:
            prob_match = re.search(r"Conversion Probability.*?:.*?(\d+)%", output)
            if prob_match:
                probability = int(prob_match.group(1))
            else:
                probability = 0
        except:
            probability = 0
            
        if "Error" not in output:
            status_text = f"Hot Lead 🔥" if score >= 75 else "Warm Lead ⚠️" if score >= 50 else "Cold Lead ❄️"
            add_activity("Lead Scored", f"{name}: {score}/100 ({status_text})", icon="🎯")
            
    return render_template("lead.html", output=output, score=score, probability=probability)

@app.route("/logo", methods=["GET", "POST"])
def logo():
    image_filename = None
    if request.method == "POST":
        business_name = request.form["name"]
        style = request.form["style"]
        color = request.form.get("color", "rose and earth")
        
        expansion_prompt = f"""
        Expand this logo concept into a detailed artistic description for an image generator.
        Business: {business_name}
        Style: {style}
        Colors: {color}
        
        Keep it concise (1-2 sentences). Focus on visual elements, lighting, and composition. 
        Exclude text from the description, focus only on the icon/graphic style.
        """
        refined_description = generate_response(expansion_prompt)
        image_filename = generate_brand_logo(refined_description)
        
        if image_filename:
            add_activity("Logo Generated", f"New identity created for {business_name}", icon="🎨")
        
    return render_template("logo.html", image_filename=image_filename)

@app.route("/deck", methods=["GET", "POST"])
def deck():
    deck_filename = None
    error = None
    if request.method == "POST":
        product_name = request.form["product_name"]
        description = request.form["description"]
        audience = request.form["audience"]
        
        deck_data = generate_pptx_content(product_name, description, audience)
        if deck_data:
            filename = f"pitch_deck_{int(time.time())}.pptx"
            deck_filename = create_pptx_file(deck_data, filename)
            add_activity("Pitch Deck Created", f"New PPTX generated for {product_name}", icon="📊")
        else:
            error = "Failed to generate pitch deck content. Please try again."
            
    return render_template("deck.html", deck_filename=deck_filename, error=error)

@app.route("/email", methods=["GET", "POST"])
def email():
    output = None
    subject = None
    body = None
    if request.method == "POST":
        product = request.form["product"]
        role = request.form["role"]
        industry = request.form["industry"]
        company_size = request.form["company_size"]
        value = request.form["value"]
        problem = request.form["problem"]
        cta = request.form["cta"]
        tone = request.form["tone"]
        
        prompt = f"""
        You are an expert B2B sales copywriter.
        Generate a professional cold outreach email based on:
        Product Description: {product}
        Recipient Role: {role}
        Industry: {industry}
        Company Size: {company_size}
        Value Proposition: {value}
        Problem Being Solved: {problem}
        Call To Action: {cta}
        Tone: {tone}

        Email Requirements:
        - 120–180 words
        - Professional and confident
        - Personalized to recipient role
        - Focus on business impact and ROI
        - No hype language
        - No emojis
        - No spammy phrases
        - Clean formatting

        Return output strictly in this format:
        Subject Line:
        (Subject)

        Email Body:
        Dear {role},

        (Email content)

        Best regards,
        [Your Name]

        Only return the final email. No explanations.
        """
        output = generate_response(prompt)
        
        if "Error" not in output:
            # Parse Subject and Body
            try:
                if "Subject Line:" in output and "Email Body:" in output:
                    subject = output.split("Subject Line:")[1].split("Email Body:")[0].strip()
                    body = output.split("Email Body:")[1].strip()
                else:
                    subject = "Outreach regarding " + product[:20]
                    body = output
            except:
                subject = "Outreach"
                body = output
            
            add_activity("Cold Email Generated", f"Email for {role} in {industry}", icon="📧")
            
    return render_template("email.html", subject=subject, body=body)

from flask import Response

@app.route("/download_email")
def download_email():
    subject = request.args.get('subject', 'Cold Email')
    body = request.args.get('body', '')
    content = f"Subject: {subject}\n\n{body}"
    return Response(
        content,
        mimetype="text/plain",
        headers={"Content-disposition": "attachment; filename=cold_email.txt"}
    )

@app.route("/download/<path:filename>")
def download_file(filename):
    return send_from_directory(os.path.join(app.static_folder, 'generated'), filename, as_attachment=True)

if __name__ == "__main__":
    app.run(debug=True)
